name: Update Repository description of pgmystery/ubuntu_vnc on DockerHub

on:
  push:
    branches:
      - main
    paths:
      - docker/vnc_ubuntu/dockerhub.md
  workflow_dispatch:

jobs:
  update_readme_description_of_ubuntu_vnc:
    name: Update Repository description of pgmystery/ubuntu_vnc on DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: pgmystery/ubuntu_vnc
          readme-filepath: ./docker/vnc_ubuntu/dockerhub.md
