user root;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    # Log everything to Docker
    access_log /dev/stdout;
    error_log  /dev/stderr info;

    server {
#         listen 443 ssl;
        listen 80;
        server_name container-desktop-proxy;

#         ssl_certificate     /etc/ssl/cert.pem;
#         ssl_certificate_key /etc/ssl/key.pem;

        # Recommended SSL settings
#         ssl_protocols TLSv1.2 TLSv1.3;
#         ssl_prefer_server_ciphers on;

        location /turn {
            proxy_pass http://webtop:3000/turn;

            proxy_http_version 1.1;

            # Required for websocket upgrades
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # ---------------------------
        # WebSocket proxy for /websockets
        # ---------------------------
        location ^~ /websockets {
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            proxy_set_header Host $proxy_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;

            proxy_pass http://${SELKIES_WS_URL}$request_uri;
        }

        # -------------------------------
        # /selkies/* proxy
        # -------------------------------
        location /selkies/ {
            proxy_pass http://${SELKIES_URL}/;
            proxy_set_header Host $proxy_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;

            add_header Access-Control-Allow-Origin "*" always;
            add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
            add_header Access-Control-Allow-Headers "*" always;
        }
    }
}
