[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/tmp/supervisord.pid

# -------------------------
# NGINX
# -------------------------
[program:nginx]
command=nginx -g "daemon off;"
priority=10
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

# -------------------------
# MediaMTX (optional)
# -------------------------
[program:mediamtx]
command=/start-mediamtx.sh
autorestart=false
exitcodes=0
startretries=0
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

# -------------------------
# noVNC Proxy (main service)
# -------------------------
# [program:novnc]
# command=/noVNC/utils/novnc_proxy --vnc %(ENV_NOVNC_REMOTE_SERVER)s --listen %(ENV_NOVNC_LISTEN_HOST)s:%(ENV_NOVNC_LISTEN_PORT)s
# priority=30
# autorestart=true
# stdout_logfile=/dev/stdout
# stderr_logfile=/dev/stderr
# stdout_logfile_maxbytes=0
# stderr_logfile_maxbytes=0
