name: Publish Docker Image ubuntu_vnc (mate)

on:
  push:
    branches:
      - main
    paths:
      - docker/vnc_ubuntu/mate/Dockerfile
      - docker/vnc_ubuntu/mate/start-vnc.sh
      - docker/vnc_ubuntu/mate/apt/**
      - docker/vnc_ubuntu/mate/usr/**
  workflow_dispatch:

jobs:
  build_mate_amd64:
    name: Build docker image on amd64
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker images (mate)
        uses: docker/build-push-action@v6
        with:
          context: ./docker/vnc_ubuntu/mate
          platforms: linux/amd64
          file: ./docker/vnc_ubuntu/mate/Dockerfile
          push: false
          tags: pgmystery/ubuntu_vnc:mate-amd64
          outputs: type=docker,dest=${{ runner.temp }}/ubuntu_vnc_mate_amd64.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_vnc-mate-amd64
          path: ${{ runner.temp }}/ubuntu_vnc_mate_amd64.tar

  build_mate_arm64:
    name: Build docker image on arm64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker images (mate)
        uses: docker/build-push-action@v6
        with:
          context: ./docker/vnc_ubuntu/mate
          platforms: linux/arm64
          file: ./docker/vnc_ubuntu/mate/Dockerfile
          push: false
          tags: pgmystery/ubuntu_vnc:mate-arm64
          outputs: type=docker,dest=${{ runner.temp }}/ubuntu_vnc_mate_arm64.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_vnc-mate-arm64
          path: ${{ runner.temp }}/ubuntu_vnc_mate_arm64.tar

  create_docker_manifest_and_push_to_dockerhub:
    name: Create Docker manifest and push docker images to DockerHub
    runs-on: ubuntu-latest
    needs:
      - build_mate_amd64
      - build_mate_arm64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Download artifact (amd64)
        uses: actions/download-artifact@v4
        with:
          name: ubuntu_vnc-mate-amd64
          path: ${{ runner.temp }}

      - name: Download artifact (arm64)
        uses: actions/download-artifact@v4
        with:
          name: ubuntu_vnc-mate-arm64
          path: ${{ runner.temp }}

      - name: Load images
        run: |
          docker load --input ${{ runner.temp }}/ubuntu_vnc_mate_amd64.tar
          docker load --input ${{ runner.temp }}/ubuntu_vnc_mate_arm64.tar

      - name: Create SHA manifest and push to DockerHub
        run: |
          docker manifest create \
            pgmystery/ubuntu_vnc:mate \
            --amend pgmystery/ubuntu_vnc:mate-amd64 \
            --amend pgmystery/ubuntu_vnc:mate-arm64
          docker manifest push pgmystery/ubuntu_vnc:mate
