name: Publish Docker Image ubuntu_vnc (xfce)

on:
  push:
    branches:
      - main
    paths:
      - docker/vnc_ubuntu/xfce/Dockerfile
      - docker/vnc_ubuntu/xfce/start-vnc.sh
      - docker/vnc_ubuntu/xfce/apt/**
      - docker/vnc_ubuntu/xfce/.config/**
  workflow_dispatch:

jobs:
  build_and_push_to_hub_xfce:
    name: Build docker image and push it to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker images (xfce)
        uses: docker/build-push-action@v6
        with:
          context: ./docker/vnc_ubuntu/xfce
          platforms: linux/amd64,linux/arm64
          file: ./docker/vnc_ubuntu/xfce/Dockerfile
          push: true
#          tags: pgmystery/ubuntu_vnc:latest,pgmystery/ubuntu_vnc:xfce
          tags: pgmystery/ubuntu_vnc:xfce
